---
title: "Data Analysis 1"
description: "Datengenerierende Prozesse"
author:
  - name: Gerda Wyssen
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
  - name: Daniel Fitze
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0003-0158-7459  
license: CC BY
citation: true
bibliography: ../../bibliography_nsci24.bib
format:
    html:
        toc: true
        code-link: true
---

# Datenanalyse

## Parameterschätzung und Hypothesentests

## Datengenerierende Prozesse, Simulation und Analyse

### DAGs


## Frequentistische und Bayesianische Statistik

Frequentistisch: Wahrscheinlichkeitslehre wird angewandt um die Wahrscheinlichkeit der Daten zu berechnen, unter der Annahme dass die Nullhypothese wahr ist.

Bayesianisch:  Wahrscheinkeitslehre wird angewandt, um die Wahrscheinlichkeit der Parameter zu berechnen.

--> aber der Unterschied ist ja nicht Hyp vs. Params. sondern die Methode/Logik hinter der Schätzung. Diese Zusammenfassung ist also nicht genügend/unklar.

In der frequentistischen Statistik wird angenommen, dass der Parameter einen _wahren Wert_ hat, den wir aber nicht kennen. Wir erhalten eine Punktschätzung (mit Fehler) für den Parameter.

In der bayesianischen Statistik nehmen wir an, dass der Parameter eine Wahrscheinlichkeitsverteilung hat, die wir schätzen können (also nicht __einen__ wahren Wert).



| Ansatz | Parameterschätzung | Hypothesentests | Statistische Kennzahlen |
|------|------|------|------|
| Frequentistisch | wahrer Wert wird geschätzt | ahrscheinlichkeit der Daten zu berechnen, unter der Annahme dass die Nullhypothese wahr ist | p-Werte, Konfidenzintervall |
| Ba


