---
title: "Neurowissenschaftliche Daten & Good Practices in der Datenverarbeitung"
description: "Herausforderungen, Datenformate und Reproduzierbarkeit."
author:
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
bibliography: ../../bibliography_nsci24.bib
format:
    html:
        toc: true
        code-link: true
---


<!-- - Programmieren von Datenverarbeitungspipelines: Datenvorverarbeitung und Visualisierung („good practices“, Data Cleaning, Reproduzierbarkeit)  -->

<!--  kennen wichtige neurowissenschaftlichen Datenformen und ihre Eigenschaften -->
<!-- - können Daten aus neurowissenschaftlichen Experimenten selber vorverarbeiten und informativ visualisieren -->

>Neuroimaging experiments result in complicated data that can be arranged in many different ways. So far there is no consensus how to organize and share data obtained in neuroimaging experiments. Even two researchers working in the same lab can opt to arrange their data in a different way. Lack of consensus (or a standard) leads to misunderstandings and time wasted on rearranging data or rewriting scripts expecting certain structure. 
>[BIDS Website (2024)](https://bids-specification.readthedocs.io/en/stable/introduction.html)

# Herausforderungen im Umgang mit neurowissenschaftlichen Daten

In der neurowissenschaftlichen Forschung werden zunehmend sehr grosse und komplexe Datensätze generiert und Daten aus unterschiedlichen Datenerhebungsverfahren sollen miteinander verknüpft werden um neue Erkenntnisse zu gewinnen. Eine sehr häufige Kombination sind beispielsweise Verhaltens- und Bildgebungsdaten, wie es in vielen fMRI-Studien der Fall ist. Das erfordert Kenntnisse der unterschiedlichen Formate und Eigenschaften der Daten und Programmierkenntnisse um diese Daten möglichst automatisiert vorzuverarbeiten, zu verknüpfen, zu visualisieren und analysieren.

:::callout-caution
## Hands-on: Herausforderungen von neurowissenschaftlichen Daten

Lesen Sie den untenstehenden Abschnitt aus @pierre_perspective_2024. Besprechen Sie in Gruppen, welche spezifischen Herausforderungen Datenmanagment, -vorverarbeitung und -analyse in den Neurowissenschaften bestehen.
:::

>__Increasing complexity of neuroscience data__
>
>Over the past 20 years, neuroscience research has been radically changed by two major trends in data production and analysis.
>
>First, neuroscience research now routinely generates large datasets of high complexity. Examples include recordings of activity across large populations of neurons, often with high resolution behavioral tracking (Steinmetz et al., 2019; Stringer et al., 2019; Mathis et al., 2018; Siegle et al., 2021; Koch et al., 2022), analyses of neural connectivity at high spatial resolution and across large brain areas (Scheffer et al., 2020; Loomba et al., 2022), and detailed molecular profiling of neural cells (Yao et al., 2023; Langlieb et al., 2023; Braun et al., 2022; Callaway et al., 2021). Such large, multi-modal data sets are essential for solving major questions about brain function (Brose, 2016; Jorgenson et al., 2015; Koch and Jones, 2016).
>
>Second, the collection and analysis of such datasets requires interdisciplinary teams, incorporating expertise in systems neuroscience, engineering, molecular biology, data science, and theory. These two trends are reflected in the increasing numbers of authors on scientific publications (Wareham, 2016), and the creation of mechanisms to support team science by the NIH and similar research funding bodies (Cooke and Hilton, 2015; Volkow, 2022; Brose, 2016).
>
>There is also an increasing scope of research questions that can be addressed by aggregating “open data” from multiple studies across independent labs. Funding agencies and publishers have begun to aggressively promote data sharing and open data, with the goals of improving reproducibility and increasing data reuse (Dallmeier-Tiessen et al., 2014; Tenopir et al., 2015; Pasquetto et al., 2017). However, open data may be unusable if scattered in a wide variety of naming conventions and file formats lacking machine-readable metadata.
>
>Big data and team science necessitate new strategies for how to best organize data, with a key technical challenge being the development of standardized file formats for storing, sharing, and querying datasets. Prominent examples include the Brain Imaging Data Structure (BIDS) for neuroimaging, and Neurodata Without Borders (NWB) for neurophysiology data (Teeters et al., 2015; Gorgolewski et al., 2016; Rübel et al., 2022; Holdgraf et al., 2019). The Open Neurophysiology Environment (ONE), best known from adoption by The International Brain Laboratory (The International Brain Laboratory et al., 2020, 2023), has a similar application domain to NWB, but a highly different technical design. 
>
>These initiatives provide technical tools for storing and accessing data in known formats, but more importantly provide conceptual frameworks with which to standardize data organization and description in an (ideally) universal, interoperable, and machine-readable way.
@pierre_perspective_2024 [(Preprint)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10593085/)
 

# Neurowissenschaftliche Daten

:::callout-caution
## Hands-on: Daten in den Neurowissenschaften

Welche Datenformen kennen Sie?


Füllen Sie in Gruppen die untenstehende Tabelle zusammen aus. Es gibt folgende Gruppen:
- EEG
- MRI
- Eye-tracking
- Verhaltensdaten




Schliessen Sie sich am besten einer Gruppe an, in der Sie das Methodenseminar absolviert haben.
:::



# Good Practices in der Datenverarbeitung

Die Replikationskrise hat in der Psychologie, aber auch in den kognitiven Neurowissenschaften ein Umdenken ausgelöst. Mit dem Ziel nachhaltigere Forschungsergebnisse zu erreichen sind verschiedene Begriffe wie Reproduzierbarkeit und Replizierbarkeit zu wichtigen Schlagworten geworden. Die Begrifflichkeiten werden verwirrenderweise aber oft unterschiedlich definiert und verwendet (@plesser_reproducibility_2018).

:::callout-caution
## Hands-on: Wichtige Begriffe 

Wichtige Begriffe hinsichtlich qualitativ guter Forschung sind

- reproducibility

- replicability

- reliability

- robustness

- generalizability

Besprechen Sie in kleinen Gruppen diese Begrifflichkeiten und schreiben Sie für jeden 1 Satz als Definition auf.

:::

## Replizierbarkeit 

_Replizierbarkeit (replicability)_ bedeutet, dass ein Experiment von einer anderen Forschungsgruppe mit einer neuen Stichprobe durchgeführt werden kann, und ähnliche oder dieselben Resultate hervorbringt, wie die Originalstudie. Wird eine Studie mehrmals repliziert, steigt die Wahrscheinlichkeit, dass kein Zufallsbefund vorliegt. 

> Replicability refers to the ability of a researcher to duplicate the results of a prior study if the same procedures are followed but new data are collected. @cacioppo_social_2015


## Reproduzierbarkeit 

_Reproduzierbarkeit (reproducibility)_ hängt eng mit der Replizierbarkeit zusammen. Der Begriff wird teilweise sehr allgemein verwendet, und bedeutet so dass Forschungsergebnisse wiederholt gefunden werden. Reproduzierbarkeit im engeren Sinn hingegen bezieht sich darauf, ob die durchgeführte Analyse wiederholt werden kann. Die Reproduzierbarkeit ist somit hoch, wenn Forschende die Daten und Datenanalyseskripts bereitstellen und andere Forschende damit dieselben Analysen durchführen können und zu gleichen Resultaten kommen.

> Reproducibility refers to the ability of a researcher to duplicate the results of a prior study using the same materials as were used by the original investigator. That is, a second researcher might use the same raw data to build the same analysis files and implement the same statistical analysis in an attempt to yield the same results…. Reproducibility is a minimum necessary condition for a finding to be believable and informative. @cacioppo_social_2015

Um die Begriffe zusammenzufassen schlugen @goodman_what_2016 vor von _Reproduzierbarkeit der Methoden_ (Daten und Prozesse können exakt wiederholt werden), _Reproduzierbarkeit der Resultate_ (andere Studien kommen auf dieselben Resultate) und _Reproduzierbarkeit der wissenschaftlichen Schlussfolgerung_ (bei Repetition der Analyse oder der Experimente werden dieselben Schlüsse gezogen) zu sprechen.

Grundsätzlich besteht das Ziel, dass in der Forschung möglichst viel Evidenz für eine Schlussfolgerung gesammelt werden kann. Dies gelingt, wenn die Prozesse transparent, fehlerfrei und wiederholbar sind.




# Reproduzierbarkeit

Im Rahmen dieses Kurses beschäftigen wir uns vor allem, wie Reproduzierbarkeit erhöht werden kann. 

## Hindernisse bei der Reproduzierbarkeit

Reproduzierbarkeit kann laut @nosek_replicability_2022 vor allem aus zwei Gründen nicht gegeben sein: Weil die Daten/Skripte nicht zur Verfügung stehen, oder weil diese Fehler enthalten:

> In principle, all reported evidence should be reproducible. If someone applies the same analysis to the same data, the same result should occur. Reproducibility tests can fail for two reasons. A process reproducibility failure occurs when the original analysis cannot be repeated because of the unavailability of data, code, information needed to recreate the code, or necessary software or tools. An outcome reproducibility failure occurs when the reanalysis obtains a different result than the one reported originally. This can occur because of an error in either the original or the reproduction study. @nosek_replicability_2022

Führt die Reproduktion nicht zum selben Resultat, löst das Zweifel am Forschungsergebnis aus. Wenn die Reproduzierbarkeit am Prozess scheitert, etwa weil die Daten nicht vorhanden sind, kann kein Schluss gezogen werden, ob die Resultate stimmen. 

> Achieving reproducibility is a basic foundation of credibility, and yet many efforts to test reproducibility reveal success rates below 100%. ... Whereas an outcome reproducibility failure suggests that the original result may be wrong, a process reproducibility failure merely indicates that the original result cannot be verified. Either reason challenges credibility and increases uncertainty about the value of investing additional resources to replicate or extend the findings (Nuijten et al. 2018). Sharing data and code reduces process reproducibility failures (Kidwell et al. 2016), which can reveal more outcome reproducibility failures (Hardwicke et al. 2018, 2021; Wicherts et al. 2011). @nosek_replicability_2022

Das Teilen von Daten und Datenverarbeitungsskripten erhöht die Wahrscheinlichkeit, dass mögliche Fehler im Prozess gefunden werden, da auch andere Forschende die Daten/Skripts verwenden können. Das ist vorerst unangenehm, gehört aber zum Prozess der Wissenschaft dazu.
Reproduzierbarkeit erhöht also indirekt auch die Replizierbarkeit.


# Tools für Reproduzierbarkeit

Für reproduzierbare Forschung gibt es inzwischen viele gute Tools:

- Website der [Open Science Foundation](https://osf.io/): Eine kostenfreie und unkomplizierte Möglichkeit Daten und Skripts zu teilen, und diese in Projekten abzulegen. Es lässt sich dafür sogar ein *doi* erstellen. Auch Preregistrationsformulare sind hier implementiert.

Beim Veröffentlichen von wissenschaftlichen Artikeln ist es empfohlen, die Daten (falls anonymisiert möglich) sowie die Analyseskripts mitzuveröffentlichen. 

- Für Datensätze gelten die _FAIR Guiding Principles_ (@wilkinson_fair_2016): 
    - **F** indability: Es ist klar unter welchen Umständen und wie die Daten zugänglich sind
    - **A** ccessibility: Daten sind zugänglich bzw. es ist klar wo sie zu finden wären
    - **I** nteroperability: Verwendbare Datenformate/strukturen
    - **R** eusability: gute Beschreibung des Datensatzes/der enthaltenen Variablen
    
<aside> [Hier](https://www.go-fair.org/fair-principles) finden Sie weitere Informationen zu _FAIR_. </aside>

- Für Neuroimaging-Daten gibt es beispielsweise vorgegebene Konventionen, wie ein Datensatz und die Verarbeitungsskripts abgespeichert werden. Ein Beispiel dafür ist [Brain Imaging Data Structure (BIDS)](https://bids.neuroimaging.io). So können Datensätze mit einer für alle verständlichen Struktur veröffentlicht und geteilt werden. @gorgolewski_brain_2016

<aside> [Hier](https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/BIDS_Overview.html) finden Sie weitere Informationen zu _BIDS_. </aside>

- Für das Veröffentlichen von Analyseskripts eignen sich Formate wie _RMarkdown_ in _R_, oder _LiveScripts_ in _MATLAB_ sehr gut. Aber auch `.r`-Skripte, wie Sie sie in dieser Veranstaltung verwenden können veröffentlicht werden.


<aside> [Hier](https://djnavarro.net/slides-starting-rmarkdown/#1) finden Sie eine sehr gut erklärte Einführung zu _RMarkdown_. </aside>


# Code kommentieren

Das Teilen von Skripts macht am meisten Sinn, wenn sie verständlich strukturiert und kommentiert sind. Beim Kommentieren von Code sollte folgendes beachtet werden:

-   Kommentare sollten geschrieben werden, wenn der Code erstellt wird und laufend überarbeitet werden. Oft wird es sonst nicht nachgeholt.

-   Wenn man nicht genau kommentieren kann, was man im Code macht, dann ist evtl. der Code unklar, oder man versteht ihn noch nicht. Vielleicht kann man Variablennamen vereinfachen/präzisieren und es braucht weniger Kommentare?

-   Wenn Code kopiert wird, sollte die Quelle angegeben werden.

-   Vor dem Veröffentlichen, lohnt es sich jemanden den Code ausführen lassen. So zeigt sich wo noch unklare Stellen sind, die Kommentare benötigen.

