---
title: "Setup"
author:
  - name: Daniel Fitze
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0003-0158-7459  
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY-SA 4.0
citation: true
bibliography: ../../bibliography.bib
format:
    html:
        toc: true
---

## In dieser Veranstaltung verwendete Software

Wir haben uns entschieden, in dieser Veranstaltung Python zu verwenden, um ein Experiment zu erstellen, und R für die Analyse der Daten. Matlab wird nicht verwendet; einerseits da es kommerziell ist, andererseits weil es aus unserer Sicht nicht die beste Wahl für die Analyse von Verhaltensdaten ist. Ausserdem ist es schon schwierig genug, eine Programmiersprache zu lernen, ohne gleichzeitig noch zwei weitere zu lernen.



## Python

Wenn Sie Python suf Ihrem Rechner installieren wollen, können Sie entweder den offiziellen Installer [https://www.python.org/downloads/](https://www.python.org/downloads/) downloaden, oder die Anaconda Distribution [https://www.anaconda.com/products/distribution](https://www.anaconda.com/products/distribution) verwenden. Die Anaconda Distribution ist eine Python-Distribution, die viele nützliche Pakete enthält, die für wissenschaftliches Rechnen und Datenanalyse verwendet werden. Wenn man tatsächlich mit Python arbeiten will, empfiehlt es sich, die Anaconda Distribution zu benutzen. Wir werden in dieser Veranstaltung Python benutzen, um ein Experiment zu programmieren. Dafür reicht es aus, den PsychoPy Installer zu verwenden; diesen finden Sie unter diesem Link: [PsychoPy](https://www.psychopy.org/). PsychoPy ist ein Python-basiertes Tool, mit dem sich sowohl in einer grafischen Benutzeroberfläche (GUI) als auch mit Python Code Experimente programmieren lassen.

## R

Ab der vierten Sitzung werden wir viel mit R arbeiten, um Daten aufzubereiten und grafisch darzustellen. Dafür müssen Sie die __aktuelle__ Version von R installieren. Diese ist zurzeit R 4.3.2, und kann unter folgender URL geladen werden: 

R 👉 [https://cloud.r-project.org/](https://cloud.r-project.org/)

Wir empfehlen für die Arbeit mit R die RStudio IDE zu verwenden. Diese ist kostenlos und kann unter folgender URL heruntergeladen werden:

RStudio 👉 [https://www.rstudio.com/products/rstudio/download/#download](https://www.rstudio.com/products/rstudio/download/#download)


## JASP

Einen Teil der Bayesianischen Analysen werden wir mit JASP durchführen. Die __aktuelle__ Version von JASP ist 0.18.3 und kann unter folgender URL heruntergeladen werden:

JASP 👉 [https://jasp-stats.org/download/](https://jasp-stats.org/download/)
