---
title: "Stroop Paradigma"
description: Programmieren eines klassischen neuropsychologischen Tests mit PsychoPy.
author:
  - name: Andrew Ellis
    url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0002-2788-936X
  - name: Gerda Wyssen
    # url: https://github.com/awellis
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
bibliography: ../../bibliography_gw.bib
format:
    html:
        toc: true
---

## 1. Stimuli

Erstellen Sie einen **Stroop Stimulus**. Beachten Sie folgende Aspekte:

- Timing (Stimulusdauer): 1500 ms

- Farbe

- Grösse: gut sichtbar

- Kohärenz: 0.08

- Field size: 75% des Displays

*(Die Bewegungsrichtung können Sie noch vernachlässigen.)*


## 2. Trialschleife

Erstellen Sie eine **Trial**-Schleife. 

- Fixation 1 (100/350/800/1200 ms) *(Zur Vereinfachung können Sie hier auch nur einen Wert wählen.)*
    
- Cue (1000 ms)
    
- Fixation 2 (3400/4000/4500/5000 ms) *(Zur Vereinfachung können Sie hier auch nur einen Wert wählen.)*
    
- Dots (1500 ms)
    
- Feedback

- Timing (ITI: Inter-Trial-Intervall)

- Antwort der Versuchsperson aufnehmen


*(Die Variation der Bewegungsrichtung und des Vorwissens können Sie noch vernachlässigen.)*


## 3. Bedingungen

- Variieren Sie die Bewegungsrichtung der Random Dots mit dem *conditions.csv* file: Bewegungsrichtung ist zu 50% rechts, zu 50% links.

- Variieren Sie den Cue fürs Vorwissen in jedem Trial mit dem *conditions.csv* file: Der Cue kann valide (4x), invalide (2x) oder neutral (4x) sein. Die Bewegungsrichtungen müssen auf alle Bedingungen gleich verteilt sein.


## 4. Instruktion und Debriefing

- Fügen Sie zu Beginn des Experiments eine Instruktion hinzu.

- Fügen Sie am Ende des Experiments ein Debriefing hinzu.


## 5. Test

Führen Sie das Experiment aus und schauen Sie sich den Datensatz an: Sind die untenstehenden Infos auf jeder Zeile vorhanden?

- Versuchspersonennummer

- Richtung des Stimulus

- Cue / Vorwissen

- Antwort der Versuchsperson

- Antwortdauer der Versuchsperson


## 6. Übungsexperiment

- Laden Sie [hier](https://kogpsy.github.io/neuroscicomplabFS23/pages/chapters/uebung_1.html) das Experiment für **Übung 1** herunter. 

- Vergleichen Sie das Experiment mit Ihrer Version, was fällt Ihnen auf?


