---
title: "Übung 3 - Plot"
description: Datensätze visualisieren.
author:
  - name: Daniel Fitze
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0003-0158-7459 
  - name: Gerda Wyssen
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
license: CC BY
citation: true
#bibliography: ../../bibliography_gw.bib
format:
    html:
        toc: true
code-line-numbers: true
---

## Auftrag

Erstellen Sie einen Plot der Stroop Daten. Verwenden Sie dazu `ggplot()`. Alle Plots und der entsprechende Code werden in der [Galerie]() auf der Kurshomepage anonym veröffentlicht.

## Vorgehen

- __Setup__

    - Laden Sie das _R-Project_ [Uebung3](../../downloadable_files/Uebung3.zip) herunter und entzippen Sie den Ordner. 
    
    - Ändern Sie den Namen der Datei _nachname_vorname_plot.R_, indem Sie Ihren Vor- und Nachnamen einsetzen.  

- __Erstellen des Plots__ (mit folgenden Schritten):

    - Öffnen Sie die die Datei _nachname_vorname_plot.R_. Der Inhalt dieser Datei muss gleich aussehen, wie im Beispiel unten. 
    
    - Der Code auf von Zeile 1 bis Zeile 9 darf __nicht verändert werden!__
    
    - Fügen Sie den Code für Ihre Abbildung ab Zeile 9 ein. 
    
    - Der eingefügte Code muss die Abbildung erstellen (vgl. Zeile 9-12) und anzeigen (vgl. Zeile 12).
    
```{r}
#| echo: true
#| eval: false

# Code innerhalb der folgenden 2 Linien darf nicht verändert werden
# ---------------------------------------------------------------------
library(tidyverse)
d = read_csv('data/dataset_stroop_clean.csv')
# ---------------------------------------------------------------------

# Beginnen Sie hier mit Ihrem Code:

p = d |>
    ggplot(...) +
    ...
p
```

- __Der Plot muss Folgendes beinhalten:__
    - Beides, Rohdaten UND mind. 1 zusammenfassendes Mass(z.B. Mittelwert mit Standardabweichungen, Box-/Violinplot, etc.). TIPP: Mehrere Geoms können übereinander gelegt werden.
    - Mind. 2 unterschiedliche Farben.
    - Beschriftungen: Titel, Subtitel, Achsenbeschriftungen, (optional: Captions)
    - Der Subtitel beinhaltet die Frage, welche der Plot beantwortet.  
    - Ein Theme verwenden.
    - Optional: Facets verwenden.

- __Hochladen Codefile auf Ilias unter `Übung 3` :__ 

    - Geben Sie die Datei _nachname_vorname_plot.R_ (umbenannt mit Ihrem Vor- und Nachnamen) auf Ilias unter `Übung 3` ab.


## Abgabetermine

__Gruppe Montag:__ 28. April 2024 23:55

__Gruppe Mittwoch:__ 30. April 2024 23:55

:::{.callout-caution}
## Wichtig
Ihr Plot und der dazugehörige Code wird in der [Galerie]() anonym veröffentlich. Deshalb ist es wichtig, dass die oben aufgelisteten Voraussetzungen erfüllt sind. 
:::

<!-- ## Trouble shooting -->


<!-- __Das Einlesen funktioniert nicht.__ -->

<!-- Kontrollieren Sie bei der `read.csv()`-Funktion das `sep = ` Zeichen. Passt dieses zum Datensatz? -->

<!-- Stimmt die Ordnerstruktur? Arbeiten Sie in einem _R-Project_, ist das `.Rmd`-File im _selben_ Ordner wie das `.Rproj`-File und haben Sie die Daten im `data`-Ordner gespeichert (ungezippt, also nur die Datenfiles)? -->

<!-- __Die Datensätze können nicht alle eingelesen werden, obwohl ein einzelner Datensatz eingelesen werden kann.__ -->

<!-- Bitte öffnen Sie die Dateien nur in R, nicht in Excel oder in einem anderen Programm, das kann die Formatierung ändern und Probleme beim Einlesen verursachen. Falls Sie die Daten schon geöffnet haben, laden Sie den Datensatz nochmals neu von der Website herunter und speichern Sie ihn im Datenordner. -->



<!-- __Weitere Fehlermeldungen__ -->

<!-- Lesen Sie die Fehlermeldung genau durch: Finden Sie Informationen zur Lösung des Fehlers? -->

<!-- _Häufigste Fehlerquellen:_ -->

<!-- - Tippfehler? -->

<!-- - Ist der Code-Chunk ist richtig formattiert: Er muss mit ` ```{r}` beginnen und mit ` ``` ` enden. Stellen Sie sicher, dass eine Lücke zum nächsten Code-Chunk besteht. -->

<!-- - Reihenfolgenfehler? Löschen Sie alle Variablen mit dem "Besen"-Symbol oben rechts und lassen Sie Ihren Code nochmals von Beginn an durch laufen. -->





__Bei Problemen, fragen Sie bitte an der nächsten Veranstaltung nach.__
