---
title: "Terminübersicht"
author:
  - name: Gerda Wyssen
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0001-7427-3149
  - name: Daniel Fitze
    # url: 
    affiliation: Kognitive Psychologie, Wahrnehmung und Methodenlehre, Universität Bern 
    affiliation-url: https://www.kog.psy.unibe.ch
    orcid: 0000-0003-0158-7459
license: CC BY
citation: false
# bibliography: ../../bibliography.bib
format:
    html:
        toc: true
---

# Termine der Leistungsnachweise


### Gruppe Montag

| Leistungsnachweis | Form |Beginn | Abgabetermin | Link | Inhalt |
|---------|:------:|:------:|:------:|:-------| :-------|
| Q1: Vorkenntnisse | Quiz auf Ilias | 19.02.2024 | 28.02.2024 23:55 | [Q1](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/quiz_one.html) | Erheben der Vorkenntnisse |
| Ü1: PsychoPy Experiment | Übung | 11.03.2024 | 21.03.2024 23:55 |[Ü1](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_1_experiment.html) | Datenerheben mit einem PsychoPy Experiment |
| Ü2: Data wrangling | Übung | 25.03.2024 | 17.04.2024 23:55 | [Ü2](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_2_datawrangling.html) | Datensätze automatisiert einlesen und vorverarbeiten |
| Ü3: Data visualization | Übung | 08.04.2024 | 28.04.2024 23:55 | [Ü3](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_3_plot.html) | Daten visualisieren: [Galerie](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/gallery_mo.html) |
| Ü4: Data analysis I | Übung | 22.04.2024 | 10.05.2024 23:55 |  | |
| Ü5: Data analysis II | Übung | 13.05.2024 | 31.05.2024 23:55 |  | |
| Q2: Kursinhalte | Quiz auf Ilias | 20.05.2024 | 27.05.2024 23:55 | | |

### Gruppe Mittwoch

| Leistungsnachweis | Form |Beginn | Abgabetermin | Link | Inhalt |
|---------|:------:|:------:|:------:|:-------| :-------|
| Q1: Vorkenntnisse | Quiz auf Ilias | 21.02.2024 | 28.02.2024 23:55 | [Q1](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/quiz_one.html) | Erheben der Vorkenntnisse |
| Ü1: PsychoPy Experiment | Übung | 13.03.2024 | 23.03.2024 23:55 |[Ü1](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_1_experiment.html) | Datenerheben mit einem PsychoPy Experiment |
| Ü2: Data wrangling | Übung | 27.03.2024 | 17.04.2024 23:55 | [Ü2](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_2_datawrangling.html) | Datensätze automatisiert einlesen und vorverarbeiten |
| Ü3: Data visualization | Übung | 10.04.2024 | 30.04.2024 23:55 | [Ü3](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/uebung_3_plot.html) | Daten visualisieren: [Galerie](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/gallery_mi.html) |
| Ü4: Data analysis I | Übung | 24.04.2024 | 12.05.2024 23:55 |  | |
| Ü5: Data analysis II | Übung | 15.05.2024 | 02.06.2024 23:55 | | |
| Q2: Kursinhalte | Quiz auf Ilias | 20.05.2024 | 27.05.2024 23:55 | | |


# Inhalte

An den 13 Sitzungen werden wir folgende Themen behandeln (kleine Änderungen vorbehalten):

### 1 Einführung

`Sitzung 1 (19./21. Februrar 2024)`

-   Einführung in Programmiersprachen und -umgebungen im neurowissenschaftlichen Kontext (Python, R, Matlab, Julia, Bash) und ihre Programmierumgebungen (z.B. RStudio, PsychoPy, usw.)

<!-- - *Hands-on: Sprachen vergleichen, Funktionen und Loops nutzen und schreiben, Verwendung LLMs, ChatGPT und RTutor.ai* -->

<!---   Verwendung von LLMs (z.B. ChatGPT) -->

-   Installieren der für den Kurs benötigten Software

-   [Datacamp-Kurse anschauen und belegen](https://kogpsy.github.io/neuroscicomplabFS24/pages/chapters/datacamp.html).

- __Quiz 1 ausfüllen (siehe Ilias)__

### 2 Experimente programmieren

`Sitzung 2 (26./28. Februrar 2024)`

`Sitzung 3 (4./6. März 2024)`

- Übersicht Leistungsnachweise, 

-   Experimente in den Neurowissenschaften: Elemente und Herausforderungen

-   Erstellen von zwei computerbasierten Experimenten mit `Python` und `PsychoPy`

-   __Übung 1: Datenerhebung__


### 3 Data Wrangling & Daten visualisieren

`Sitzung 4 (11./13. März 2024)`

`Sitzung 5 (18./20. März 2024)`

`Sitzung 6 (25./27. März 2024)`

*Ferien: 1./3. April: Vorlesungsfreie Zeit*

`Sitzung 7 (8./.10. April 2024)`

`Sitzung 8 (15./17. April 2024)`

- Arbeiten in `R` mit Projekten und `Rmarkdown`

- Daten mit `R` einlesen, bearbeiten und visualisieren

- Datenverarbeitung automatisieren

- Open Science, Reproduzierbarkeit und Datenmanagement: wie neurowissenschaftliche Daten und Datenverarbeitungspipelines sinnvoll gestaltet und geteilt werden können

- __Übung 2 und 3: Datenverarbeiten und visualisieren__


### 4 Analysemethoden 

`Sitzung 8 (15./17. April 2024)`

`Sitzung 9 (22./24. April 2024)`

`Sitzung 10 (29. April und 1. Mai 2024)`

- Besonderheiten neurowissenschaftlicher Daten und Analysen

- frequentistische und bayesianische Analyseverfahren

- __Übung 4: Datensatz analysieren__


### 5 Modellieren von neurowissenschaftlichen Daten

`Sitzung 11 (6../8. Mai 2024)`

`Sitzung 12 (13./15. Mai 2024)`

*Termine von Mo 20. Mai 2024 und Mi 22. Mai 2024  fallen aus (Pfingstmontag) stattdessen wird Quiz 2 ausgefüllt.*

`Sitzung 13 (27./29. Mai 2014)`

- Signalentdeckungstheorie (signal detection theory, SDT)

- Drift Diffusion Models (DDM)

- __Quiz 2: Abschlussquiz__

- __Übung 5: Datensatz analysieren__


